# Generated by Django 4.1.3 on 2022-11-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=400, verbose_name='Описание')),
                ('status', models.CharField(default='new', max_length=50, verbose_name='Статус')),
                ('deadline', models.DateField(blank=True, default='', null=True, verbose_name='к дате')),
            ],
        ),
    ]
