# Generated by Django 4.1.3 on 2022-11-04 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_rename_article_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='created_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
    ]
