# Generated by Django 4.1.3 on 2022-11-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0005_alter_todolist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='name',
            field=models.CharField(default='task', max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
