# Generated by Django 4.1.3 on 2022-11-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0006_todolist_name_alter_todolist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
